stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace browteco.xcworkspace -scheme SchemeName | xcpretty
    - xcodebuild test -workspace browteco.xcworkspace -scheme SchemeName -destination 'platform=iOS Simulator','name=iPhone 6s,OS=9.2' | xcpretty -s
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11
