language: objective-c
osx_image: xcode7.3
xcode_workspace: browteco.xcworkspace
xcode_scheme: browteco
xcode_sdk: iphonesimulator9.3
script:
- xctool -workspace browteco.xcworkspace -scheme browteco -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool -workspace browteco.xcworkspace -scheme browtecoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test
env:
  global:
  - APP_NAME="browteco"
  - 'DEVELOPER_NAME="iPhone Distribution: Joao Paulo Alves (F4V48FFS39)"'
  - PROFILE_NAME="iOS_Team_Provisioning_Profile_"
  - secure: Eq7+rYDPcc0pFaJkpkeacri3UDkGivBLP3dmN3kWELORaNW2RW5Qk9cHRsFNweMZq5jQuBABlJQgRxJFNL0drJ5W5feysgm4zeiR+FnX6IPscQBZv5CK74mZCdt9ZNLOndnI2opwtkFt9mX/9x/vuYfPvKRQ2JKW+cp66kHUGSpKp7BE2BvsTUFWfcUq3OWg1rcjhleqeC6BjSPqIRUmnrUvnvRAAbSkNe4afum3vGmfnq+nzk8lsaex7KaxKzZIKwKsFUKiEk1lYAtSmkyNq36e6fSER5t6TCe3JmQcWmPNO6RsiR4v+yiVnsYh7XVCKU8gMl0rR9108lCygujAqnrlIub9s7eS8lvCxQQThcqF/96l8/MaJqEH23NtK7ztUVcWjL05fc0bm7K2sAcybtUWJzHNw6yRLjUtObxZCPvC10LnWZlO5Td099++v1ZLD/PQimNXiVtmkkxG3G7U4quzZsLVSplGNGtsbIbazfaffHfwxdVrm7m7Mog3KoZHha41TtLvCIyV6d+24AvoVGdaq41sTxwOgD4sMQWpS0UJJ52nlpoWmxlCeJ92D7c6PzXviPgbIK69pLrE2synYEsybnZT2e/Ts9EB4ptsSuIl0QmRDOUxYfijTS6+e2MWdbCfyf9WGbieDImGzXuvoPFBhuH+kPPUKdg6eWwIvpU=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/iOS_Team_Provisioning_Profile_.mobileprovision.enc
  -d -a -out scripts/profile/iOS_Team_Provisioning_Profile_.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/distbrowteco.mobileprovision.enc
  -d -a -out scripts/profile/distbrowteco.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/ios_development.cer.enc
  -d -a -out scripts/certs/ios_development.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dev.p12.enc -d -a
  -out scripts/certs/dev.p12
- chmod a+x ./scripts/add-key.sh
- ./scripts/add-key.sh
- chmod a+x ./scripts/remove-key.sh
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
