language: objective-c
osx_image: xcode7.3
script:
- xcodebuild -workspace browteco.xcworkspace -scheme browteco -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool -workspace browteco.xcworkspace -scheme browteco -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace browteco.xcworkspace -scheme browtecoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
env:
  global:
  - APP_NAME="browteco"
  - 'DEVELOPER_NAME="iPhone Distribution: Joao Paulo Alves (F4V48FFS39)"'
  - PROFILE_NAME="distbrowteco"
  - secure: ByNSZ5SiFozlrvMriIjperbHB3FxMiA7QMgIu/wYcp2ToA2qbOQPHCNSIqIAq3XIQ2cTLBDPN6OVDfzfPrnx4ypVjVHq1Z9W54tgUS7FDRpw6mSrVPt8lyEDtsbnkjHp/oOa2OkquUSgqTbVjUH1PClHB8cWBRecTrI92il+LRkHKSlKyMWT+IaE9Tw9QERsJG5c1ho13QR9d+pRFuLr3lW+osBEnCF/ECaBPfL4LYLdelk1Rk5tKczJVtqa0Li5+VTpDviy+xELUBXIu9SrPX7eZfjarfg4u+rDB2VvGdO6U0vlk9GqgrxnY8vDPMop08QYK6dWAmL15/jxpVCAoV0cftU0Eu5vnz8pmOUiNIbWga1DciQUZZ7S8ZeP2W9lbRGCM4DJhGySIfcGvEEZpN5OX6KAy4j77/KgDFq+lewd1/VstJMXoQupKRYVkCGywn7h4Zlr7X8kpolNFd+PMJuEAM/kLdtKaLfv1BkcrcPNAe6HOS7xaz/twVrwNeitq8CqH0F2f8XBti8Q+mAoFNq1HvSji1EmSjMgSLYgHJ5fC0BgVj2tg3VJFSSTZMT1E5s/0nKWoCEp7oACo++6DqVNmWdaGeY9hYqu0+j9hK/KUTt8FfMmlxjpLX0BgxGvEjnHu+Es9Q/iZQhDtspjaY6vETUfINmVmPdwaTZntME=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/distbrowteco.mobileprovision.enc -d -a -out scripts/profile/distbrowteco.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- chmod a+x ./scripts/add-key.sh
- ./scripts/add-key.sh
- chmod a+x ./scripts/update-bundle.sh
- ./scripts/update-bundle.sh
- chmod a+x ./scripts/remove-key.sh
- ./scripts/remove-key.sh
script:
- xctool -workspace browteco.xcworkspace -scheme browteco -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
