language: objective-c  #1
osx_image: xcode7.3 #2
xcode_workspace: browteco.xcworkspace #3
xcode_scheme: browteco #4
xcode_sdk: iphonesimulator9.3 #5
script:
  - xctool -workspace browteco.xcworkspace -scheme browteco -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace browteco.xcworkspace -scheme browtecoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
