language: objective-c
osx_image: xcode7.3
xcode_workspace: browteco.xcworkspace
xcode_scheme: browteco
xcode_sdk: iphonesimulator9.3
script:
- xctool -workspace browteco.xcworkspace -scheme browteco -sdk iphoneos -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xctool test -workspace browteco.xcworkspace -scheme browtecoTests -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
env:
  global:
  - APP_NAME="browteco"
  - 'DEVELOPER_NAME="iPhone Distribution: Joao Paulo Alves (F4V48FFS39)"'
  - PROFILE_NAME="iOS_Team_Provisioning_Profile_"
  - secure: vThXm5smOEZBPo+wpKa0BoqJBqxXPCOfuvs6GoN31h0p73fdsdjckoMnwR+3PlitktZJDMr5zV8TUX/3jaT7LJkDkzJXfG6Bgp+E1cHKjEpddp1aeTgmO+AIqN6VrQoIB93rNEVegQbsTEMNytYQRtVk4/pC5ycBJtYUJoCGE0xIke3DzCcskbRof+Qwr1c2PcRNw3y7jh2lzriyRmm9JPGlj0Rztbzsw7E9+AreJiskMRuSKpvBlYtoTXby922Wg7+1YlULahvul1SlMTgv8uzqWjA5w5h35fpqRAtUSnkAMv1fE73LT4NzlwDVa+FyVk+x0TepB9RJyK+yhGPSPFLWPreFR1tPAVIwyTcOfe9vIuUtkENJ2gYTmI2lZXe8Nkt7irhpZKehkPXhJ/g7y/kdHdtnkO2X3gqGv/VCD0e6LLNRGWTmOeK608zINJNDTu54XrwF9t/wEhBpBVO/+o0tLMUn51XnV2X0d7N0GZVrjw66wZj2aWrgJz0XX6PFqGQ5CTUUxnwnQYQOB8mVaHHiFM/XSWAJfGb+VxHk1tG9Yr7fz+mGP2VNWfp6Mli6b7HlLdm2BntI+emYqXhGzX4R9/5tkrgmv5jafekAE186cMH1Lvp2vmc/S8upC6aeKQhCZFH0D28xEOsFWItP9WtZfBrBtJj6N26FxHFQFi0=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/iOS_Team_Provisioning_Profile_.mobileprovision.enc
  -d -a -out scripts/profile/iOS_Team_Provisioning_Profile_.mobileprovision

- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12

- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/ios_development.cer.enc -d -a
  -out scripts/certs/ios_development.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dev.p12.enc -d -a
  -out scripts/certs/dev.p12

- chmod a+x ./scripts/add-key.sh
- ./scripts/add-key.sh
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
